server:
  port: 8600
spring:
  application:
    name: PORUCIVANJE-PROIZVODA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost